### ISSUE TITLE
Cannot get 0.9 version to work in Apache NetBeans 19.0

### ISSUE THREAD

**Issue by jkovalsky** [sudeephazra/perl-on-netbeans#12]
Product Version: Apache NetBeans IDE 19
Java: 19.0.2; OpenJDK 64-Bit Server VM 19.0.2+7-44
Runtime: OpenJDK Runtime Environment 19.0.2+7-44
System: Linux version 5.15.0-117-generic running on amd64; UTF-8; cs_CZ (nb)

I somehow managed to install the perl-on-netbeans-0.9.nbm plugin into my Apache NetBeans 19, but I can neither open my existing Perl project, nor create new ones. Also Perl specific widgets in the UI are not displayed. I have found this exception in the IDE log:

[UnsupportedClassVersionError.txt](https://github.com/user-attachments/files/16471554/UnsupportedClassVersionError.txt)

**Comment by sudeephazra** [comment]
Thanks for reporting this @jkovalsky 

I will take a look into this over the weekend.

**Comment by jkovalsky** [comment]
I am seeing the same problem in Apache NetBeans 18 too:

Product Version: Apache NetBeans IDE 18
Java: 19.0.2; OpenJDK 64-Bit Server VM 19.0.2+7-44
Runtime: OpenJDK Runtime Environment 19.0.2+7-44
System: Linux version 5.15.0-117-generic running on amd64; UTF-8; cs_CZ (nb)

I forgot to mention that after installation this exception was also thrown, although I am not 100 % sure it is related:

[NullPointerException.txt](https://github.com/user-attachments/files/16472436/NullPointerException.txt)

**Comment by sudeephazra** [comment]
Noted @jkovalsky

**Comment by sudeephazra** [comment]
For Netbeans 18, I am unable to replicate and have the following. Code execution is also working 😎 

OS: Windows 11 build 22631.3880
Product Version: Apache NetBeans IDE 18
openjdk 21.0.2 2024-01-16 LTS
OpenJDK Runtime Environment Zulu21.32+17-CA (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Zulu21.32+17-CA (build 21.0.2+13-LTS, mixed mode, sharing)

![image](https://github.com/user-attachments/assets/2ff28814-0316-489c-a71f-f1ae1199e51f)

**Comment by sudeephazra** [comment]
On Netbeans 19, I am getting an error as below during the install of the plugin. Looking into it.

```
java.nio.file.NoSuchFileException: C:\Users\Sudeep\Downloads\netbeans-19\ide\modules\org-netbeans-modules-xml-text.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:197)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1853)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1445)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:724)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:345)
	at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:100)
	at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:192)
	at java.base/sun.net.www.protocol.jar.JarFileFactory.getOrCreate(JarFileFactory.java:91)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:110)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:153)
	at org.netbeans.core.startup.layers.BinaryFS$BFSFile.getInputStream(BinaryFS.java:863)
Caused: java.io.FileNotFoundException: Cannot find 'jar:file:/C:/Users/Sudeep/Downloads/netbeans-19/ide/modules/org-netbeans-modules-xml-text.jar!/org/netbeans/modules/xml/text/resources/DTDIndentEngine.xml'
	at org.netbeans.core.startup.layers.BinaryFS$BFSFile.getInputStream(BinaryFS.java:866)
	at org.openide.filesystems.MultiFileObject.getInputStream(MultiFileObject.java:640)
	at org.openide.filesystems.MultiFileObject.getInputStream(MultiFileObject.java:640)
	at org.netbeans.modules.openide.loaders.FileEntityResolver$DTDParser.parse(FileEntityResolver.java:390)
Caused: java.io.IOException: Parsing MultiFileObject@4dce1427[Services/IndentEngine/org-netbeans-modules-xml-text-settings-DTDIndentEngine.settings]: Cannot find 'jar:file:/C:/Users/Sudeep/Downloads/netbeans-19/ide/modules/org-netbeans-modules-xml-text.jar!/org/netbeans/modules/xml/text/resources/DTDIndentEngine.xml'
	at org.netbeans.modules.openide.loaders.FileEntityResolver$DTDParser.parse(FileEntityResolver.java:420)
	at org.netbeans.modules.openide.loaders.FileEntityResolver.getEnvForIDO(FileEntityResolver.java:146)
	at org.netbeans.modules.openide.loaders.FileEntityResolver.getEnvironment(FileEntityResolver.java:139)
	at org.openide.loaders.Environment.findForOne(Environment.java:106)
	at org.openide.loaders.InstanceDataObject.getCookiesLookup(InstanceDataObject.java:690)
	at org.openide.loaders.InstanceDataObject.getCookiesLookup(InstanceDataObject.java:681)
	at org.openide.loaders.InstanceDataObject.getCookieFromEP(InstanceDataObject.java:598)
	at org.openide.loaders.InstanceDataObject.getCookie(InstanceDataObject.java:628)
	at org.openide.loaders.FolderInstance.acceptDataObject(FolderInstance.java:392)
	at org.openide.loaders.FolderInstance.defaultProcessObjects(FolderInstance.java:773)
	at org.openide.loaders.FolderInstance.access$000(FolderInstance.java:78)
	at org.openide.loaders.FolderInstance$1R.init(FolderInstance.java:668)
	at org.openide.loaders.FolderInstance$1R.run(FolderInstance.java:703)
	at org.openide.loaders.FolderLookup.postCreationTask(FolderLookup.java:235)
	at org.openide.loaders.FolderInstance.processObjects(FolderInstance.java:745)
	at org.openide.loaders.FolderInstance$Listener.finished(FolderInstance.java:1034)
	at org.openide.loaders.FolderList.createBoth(FolderList.java:854)
	at org.openide.loaders.FolderList.getObjects(FolderList.java:539)
	at org.openide.loaders.FolderList.access$600(FolderList.java:52)
	at org.openide.loaders.FolderList$ListTask.computeResult(FolderList.java:938)
	at org.openide.loaders.FolderList$ListTask.run(FolderList.java:914)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.openide.util.RequestProcessor$Processor.doEvaluate(RequestProcessor.java:2087)
	at org.openide.util.RequestProcessor$Task.waitFinished(RequestProcessor.java:1651)
	at org.openide.loaders.FolderInstance.waitFinished(FolderInstance.java:307)
	at org.openide.loaders.FolderInstance.instanceCreate(FolderInstance.java:256)
	at org.openide.loaders.FolderLookup.instanceForCookie(FolderLookup.java:197)
	at org.openide.loaders.FolderInstance$HoldInstance.instanceCreate(FolderInstance.java:1132)
	at org.openide.loaders.FolderLookup.createInstance(FolderLookup.java:141)
	at org.openide.loaders.FolderInstance.defaultProcessObjectsFinal(FolderInstance.java:863)
	at org.openide.loaders.FolderInstance$1R.run(FolderInstance.java:705)
	at org.openide.loaders.FolderLookup.postCreationTask(FolderLookup.java:235)
	at org.openide.loaders.FolderInstance.processObjects(FolderInstance.java:745)
	at org.openide.loaders.FolderInstance$Listener.finished(FolderInstance.java:1034)
	at org.openide.loaders.FolderList.createBoth(FolderList.java:854)
	at org.openide.loaders.FolderList.getObjects(FolderList.java:539)
	at org.openide.loaders.FolderList.access$600(FolderList.java:52)
	at org.openide.loaders.FolderList$ListTask.computeResult(FolderList.java:938)
	at org.openide.loaders.FolderList$ListTask.run(FolderList.java:914)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
```

**Comment by sudeephazra** [comment]
When I close the IDE v19 and re-open it, I see all functionalities are working 😕 

I was also able to execute the code successfully.

![image](https://github.com/user-attachments/assets/79823488-b478-4386-b2d1-edbe59234edb)

**Comment by sudeephazra** [comment]
@jkovalsky Can you please advise how to proceed.

**Comment by jkovalsky** [comment]
Have you tried running your plugin in NetBeans 18/19 with Java 19.0.2 [1]? Also, any chance to test it on Linux, not Windows?
[1] [https://www.oracle.com/java/technologies/javase/jdk19-archive-downloads.html](https://www.oracle.com/java/technologies/javase/jdk19-archive-downloads.html)

**Comment by sudeephazra** [comment]
I will try this with JDK 19 on Ubuntu and update here.
