### ISSUE TITLE
NPE when invoking code completion

### ISSUE THREAD

**Issue by jkovalsky** [sudeephazra/perl-on-netbeans#6]
When trying to invoke code completion in *.pl file I get a NullPointerException instead of useful suggestions. On a side note, the plugin version is 0.6 although the filename says perl-on-netbeans-0.7.nbm, which is confusing.

Steps to reproduce:

1. Install the Perl on NetBeans plugin in Apache NetBeans 21.
2. Invoke **File > New Project...** from main menu.
3. Select **Perl** category, select **Perl Project** and click **Next >** and **Finish** buttons.
4. Invoke **File > New File...** from main menu.
5. Select **Perl** category, select **New Perl File** type and click **Next >** and **Finish** buttons.
6. Set cursor at line 9 and press Ctrl+Space.

**Expected behavior:** Code completion is shown.
**Actual behavior:** **Please wait...** popup window is shown and Notifications window contains Unexpected Exception entry.

Product Version: Apache NetBeans IDE 21
Java: 21.0.1; Java HotSpot(TM) 64-Bit Server VM 21.0.1+12-LTS-29
Runtime: Java(TM) SE Runtime Environment 21.0.1+12-LTS-29
System: Linux version 5.15.0-112-generic running on amd64; UTF-8; cs_CZ (nb)

`java.lang.NullPointerException: Cannot invoke "java.awt.Image.getProperty(String, java.awt.image.ImageObserver)" because "image" is null
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:255)
	at org.language.perl.completion.PerlKeywordCompletionItem.<clinit>(PerlKeywordCompletionItem.java:31)
Caused: java.lang.ExceptionInInitializerError
	at org.language.perl.completion.PerlCompletionProvider$1.query(PerlCompletionProvider.java:69)
	at org.netbeans.spi.editor.completion.support.AsyncCompletionTask.run(AsyncCompletionTask.java:198)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
`

**Comment by sudeephazra** [comment]
Fixed in [6ac6db92ae07d7e100a8325fa5852bc519f6e1e4](https://github.com/sudeephazra/perl-on-netbeans/commit/6ac6db92ae07d7e100a8325fa5852bc519f6e1e4)
